name: Building New Experimental Profile Resume
on:
  push:
    branches:
      - dev
    paths:
      - "profiles/*/*.json"
      - ".github/workflows/build_dev_profile_resume.yaml"

jobs:
  #! NOTICE: Make sure to add any new profile names to this matrix if you want it to be generated!
  build:
    strategy:
      matrix:
        resumefiles: [ece]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "dev"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          npm ci
          npm i jsonresume-theme-macea-${{ matrix.resumefiles }}@latest
          pip install pypdf

      - name: Build ${{ matrix.resumefiles }} profile resume
        env:
          PROFILE: ${{ matrix.resumefiles }}
          THEME: jsonresume-theme-macea-${{ matrix.resumefiles }}
        run: npm run build:profile

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            profiles/${{ matrix.resumefiles }}/resume.pdf
            profiles/${{ matrix.resumefiles }}/resume.html
          commit-msg: Update resources
          allow-removing: true
          branch: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
